### ISSUE TITLE
Todo component update 

### ISSUE THREAD

**Issue by MostafaMohamed2002** [MostafaMohamed2002/TodoTracker#10]
- [x] add completed checkbox 
- [x] remove priority icon and use card color stroke instead 
- [x] add due date with material date picker
- [x] add due time
